# Generated by Django 2.0.2 on 2018-03-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
    ]
