# Generated by Django 2.0.2 on 2018-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180306_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name_plural': 'News'},
        ),
    ]
