# Generated by Django 2.0.2 on 2018-03-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AP2047',
            new_name='C_106_1_SIO1',
        ),
    ]
