# Generated by Django 2.0.2 on 2018-03-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180305_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C_106_1_SIO1',
            new_name='C_ap2047',
        ),
    ]
