# Generated by Django 2.0.2 on 2018-03-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180305_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('handout', models.FileField(blank=True, null=True, upload_to='course/')),
                ('handout_type', models.CharField(choices=[('LC', 'Lecture'), ('AP', 'Appendix')], default='LC', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='C_ap2047',
        ),
    ]
