# Generated by Django 2.0.2 on 2018-03-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180305_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.ClassName'),
        ),
    ]
