# Generated by Django 2.0.2 on 2018-03-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['date']},
        ),
    ]
