# Generated by Django 2.0.2 on 2018-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180305_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['class_name', '-date']},
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
