# Generated by Django 2.0.2 on 2018-03-06 12:07

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180305_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='handout',
            field=models.FileField(blank=True, null=True, upload_to=course.models.Course.content_file_name),
        ),
    ]
