# Generated by Django 2.0.2 on 2018-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=30)),
                ('chinese', models.CharField(max_length=30)),
                ('identity', models.CharField(choices=[('PD', 'Postdoctoral'), ('FA', 'Full-time Assistant'), ('Ps', 'PhD Student'), ('Ms', 'Master Studnet')], default='Ms', max_length=2)),
            ],
        ),
    ]
