# Generated by Django 2.0.2 on 2018-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=30)),
                ('chinese', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=15)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('identity', models.CharField(choices=[('VP', 'Visiting Proffesor'), ('PD', 'Postdoctoral')], default='VP', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='identity',
            field=models.CharField(choices=[('PD', 'Postdoctoral'), ('FA', 'Full-time Assistant'), ('Ps', 'PhD Student'), ('Ms', 'Master Studnet')], default='PD', max_length=2),
        ),
    ]
