# Generated by Django 2.0.2 on 2018-03-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180302_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastMem',
            new_name='Past',
        ),
    ]
