# Generated by Django 2.0.2 on 2018-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180302_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=10)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='chinese',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='past',
            name='chinese',
            field=models.CharField(max_length=10),
        ),
    ]
