# Generated by Django 2.0.2 on 2018-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='identity',
            field=models.CharField(choices=[('PD', 'Philosophiæ Doctor'), ('MD', 'Master')], default='PD', max_length=2),
        ),
    ]
