# Generated by Django 2.0.2 on 2018-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_graduate_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='identity',
            field=models.CharField(choices=[('PD', 'Postdoctoral'), ('FA', 'Full-time Assistant'), ('PS', 'PhD Student'), ('MS', 'Master Studnet')], default='PD', max_length=2),
        ),
    ]
