# Generated by Django 2.0.2 on 2018-03-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20180304_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate',
            options={'ordering': ['-end']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['english']},
        ),
        migrations.AlterModelOptions(
            name='past',
            options={'ordering': ['-end']},
        ),
    ]
