# Generated by Django 2.0.2 on 2018-05-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20180307_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='JYLiu_CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
    ]
