# Generated by Django 2.0.2 on 2018-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_jyliu_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jyliu_cv',
            options={'verbose_name': 'JYLiu CV', 'verbose_name_plural': 'JYLiu CV'},
        ),
        migrations.AddField(
            model_name='member',
            name='thumb',
            field=models.ImageField(default='member_thumbnails/member_thumb.png', upload_to='member_thumbnails/'),
        ),
    ]
