# Generated by Django 2.0.2 on 2018-08-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20180821_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumb',
            field=models.FileField(default='member_thumbnails/member_thumb.png', upload_to='paper/'),
        ),
    ]
