# Generated by Django 2.1 on 2018-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20180829_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='thumb',
            field=models.FileField(blank=True, default='member_thumbnails/member_thumb.png', upload_to='paper/'),
        ),
    ]
