# Generated by Django 2.1 on 2018-09-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20180830_1232'),
        ('member', '0013_auto_20180830_1304'),
    ]

    operations = [
    ]
