# Generated by Django 2.0.2 on 2018-03-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_oral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oral',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
