# Generated by Django 2.0.2 on 2018-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_auto_20180306_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.DateField(max_length=200),
        ),
    ]
