# Generated by Django 2.0.2 on 2018-03-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20180306_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start', '-end']},
        ),
        migrations.AlterModelOptions(
            name='oral',
            options={'ordering': ['-date']},
        ),
    ]
