# Generated by Django 2.0.2 on 2018-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='domestic',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='international',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
