# Generated by Django 2.0.2 on 2018-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20180302_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='international',
            name='paper',
            field=models.FileField(blank=True, null=True, upload_to='paper/'),
        ),
    ]
