# Generated by Django 2.0.2 on 2018-03-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20180302_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['NO']},
        ),
        migrations.AlterModelOptions(
            name='domestic',
            options={'ordering': ['NO']},
        ),
        migrations.AlterModelOptions(
            name='international',
            options={'ordering': ['NO']},
        ),
    ]
