# Generated by Django 2.0.2 on 2018-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20180307_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List', models.FileField(blank=True, null=True, upload_to='paper/')),
            ],
        ),
    ]
