# Generated by Django 2.0.2 on 2018-08-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_publication_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication_list',
            options={'verbose_name': 'Publications List', 'verbose_name_plural': 'Publications List'},
        ),
    ]
