# Generated by Django 2.1 on 2018-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_auto_20180821_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='domestic',
            options={'ordering': ['-no']},
        ),
        migrations.AlterModelOptions(
            name='international',
            options={'ordering': ['-no']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='NO',
        ),
        migrations.RemoveField(
            model_name='domestic',
            name='NO',
        ),
        migrations.RemoveField(
            model_name='international',
            name='NO',
        ),
        migrations.AddField(
            model_name='book',
            name='no',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='domestic',
            name='no',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='domestic',
            name='year',
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name='international',
            name='no',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='international',
            name='year',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='international',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='international',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='international',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication_list',
            name='List',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
    ]
