# Generated by Django 2.1 on 2018-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_auto_20180909_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='domestic',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='international',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='international',
            name='paper',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='international',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication_list',
            name='List',
            field=models.FileField(null=True, upload_to='paper/'),
        ),
    ]
