# Generated by Django 2.0.2 on 2018-03-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180306_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='research',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.Organization'),
        ),
        migrations.AlterField(
            model_name='research',
            name='organization',
            field=models.CharField(max_length=200),
        ),
    ]
