# Generated by Django 2.0.2 on 2018-03-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180306_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='organization',
            new_name='organizatio',
        ),
    ]
