# Generated by Django 2.0.2 on 2018-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20180306_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-start', '-end'], 'verbose_name_plural': 'Researches'},
        ),
        migrations.RenameField(
            model_name='research',
            old_name='org',
            new_name='organization',
        ),
    ]
