# Generated by Django 2.0.2 on 2018-03-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20180306_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='organizatio',
        ),
    ]
