# Generated by Django 2.0.2 on 2018-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_research_organizatio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
